name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Tidy modules
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: Turnstyle
      if: ${{ github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Image
      run: docker build --file Dockerfile --tag hole.casa:latest .
    
    - name: Push to GitHub
      if: ${{ github.repository == 'holedaemon/hole.casa' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag hole.casa:latest ghcr.io/holedaemon/hole.casa:latest
        docker push ghcr.io/holedaemon/hole.casa:latest