// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/base.qtpl:1
package templates

//line internal/web/templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/base.qtpl:2
type Page interface {
//line internal/web/templates/base.qtpl:2
	Title() string
//line internal/web/templates/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:2
	Head() string
//line internal/web/templates/base.qtpl:2
	StreamHead(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:2
	WriteHead(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:2
	Body() string
//line internal/web/templates/base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:2
}

//line internal/web/templates/base.qtpl:10
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:10
	qw422016.N().S(`
<!DOCTYPE html>
<html>
	<head>
		<title>`)
//line internal/web/templates/base.qtpl:14
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:14
	qw422016.N().S(`</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		`)
//line internal/web/templates/base.qtpl:17
	p.StreamHead(qw422016)
//line internal/web/templates/base.qtpl:17
	qw422016.N().S(`
	</head>
	<body>
		`)
//line internal/web/templates/base.qtpl:20
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:20
	qw422016.N().S(`
	</body>
</html>
`)
//line internal/web/templates/base.qtpl:23
}

//line internal/web/templates/base.qtpl:23
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:23
	StreamPageTemplate(qw422016, p)
//line internal/web/templates/base.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:23
}

//line internal/web/templates/base.qtpl:23
func PageTemplate(p Page) string {
//line internal/web/templates/base.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:23
	WritePageTemplate(qb422016, p)
//line internal/web/templates/base.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:23
	return qs422016
//line internal/web/templates/base.qtpl:23
}

//line internal/web/templates/base.qtpl:26
type BasePage struct{}

//line internal/web/templates/base.qtpl:27
func (p *BasePage) StreamHead(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:27
}

//line internal/web/templates/base.qtpl:27
func (p *BasePage) WriteHead(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:27
	p.StreamHead(qw422016)
//line internal/web/templates/base.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:27
}

//line internal/web/templates/base.qtpl:27
func (p *BasePage) Head() string {
//line internal/web/templates/base.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:27
	p.WriteHead(qb422016)
//line internal/web/templates/base.qtpl:27
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:27
	return qs422016
//line internal/web/templates/base.qtpl:27
}

//line internal/web/templates/base.qtpl:28
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:28
}

//line internal/web/templates/base.qtpl:28
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:28
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:28
}

//line internal/web/templates/base.qtpl:28
func (p *BasePage) Title() string {
//line internal/web/templates/base.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:28
	p.WriteTitle(qb422016)
//line internal/web/templates/base.qtpl:28
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:28
	return qs422016
//line internal/web/templates/base.qtpl:28
}

//line internal/web/templates/base.qtpl:29
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:29
}

//line internal/web/templates/base.qtpl:29
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:29
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:29
}

//line internal/web/templates/base.qtpl:29
func (p *BasePage) Body() string {
//line internal/web/templates/base.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:29
	p.WriteBody(qb422016)
//line internal/web/templates/base.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:29
	return qs422016
//line internal/web/templates/base.qtpl:29
}
