// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/index.qtpl:1
package templates

//line internal/web/templates/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/index.qtpl:1
type Member struct {
	Name      string `json:"name"`
	Nick      string `json:"nick"`
	AvatarURL string `json:"avatar_url"`
	Bot       bool   `json:"bot"`
}

//line internal/web/templates/index.qtpl:10
type IndexPage struct {
	Members []*Member
}

//line internal/web/templates/index.qtpl:15
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:15
	qw422016.N().S(`
Casa de Hole
`)
//line internal/web/templates/index.qtpl:17
}

//line internal/web/templates/index.qtpl:17
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:17
	p.StreamTitle(qw422016)
//line internal/web/templates/index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:17
}

//line internal/web/templates/index.qtpl:17
func (p *IndexPage) Title() string {
//line internal/web/templates/index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:17
	p.WriteTitle(qb422016)
//line internal/web/templates/index.qtpl:17
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:17
	return qs422016
//line internal/web/templates/index.qtpl:17
}

//line internal/web/templates/index.qtpl:19
func (p *IndexPage) StreamHead(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:19
	qw422016.N().S(`
<link rel="stylesheet" href="/static/index.css">
`)
//line internal/web/templates/index.qtpl:21
}

//line internal/web/templates/index.qtpl:21
func (p *IndexPage) WriteHead(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:21
	p.StreamHead(qw422016)
//line internal/web/templates/index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:21
}

//line internal/web/templates/index.qtpl:21
func (p *IndexPage) Head() string {
//line internal/web/templates/index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:21
	p.WriteHead(qb422016)
//line internal/web/templates/index.qtpl:21
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:21
	return qs422016
//line internal/web/templates/index.qtpl:21
}

//line internal/web/templates/index.qtpl:23
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:23
	qw422016.N().S(`
<header id="header">
    <h1 class="title">Casa de Hole</h1>
    <p class="subtitle">Notice: the official Casa de Hole website is maintained by an idiot. This information can be copied and distributed, however, any unauthorized alteration of any portion of the Casa de Hole website is a violation of my nuts.</p>

    <h1 id="weapon-sex-title" class="title">Weapon Sex</h1>
    <p class="subtitle">The most notorious members of the Hole. <span class="warning">SHOULD ALWAYS BE CONSIDERED ARMED AND DANGEROUS (AND MOSTLY GAY)</span>. If you encounter any of these members, <span class="warning">DO NOT APPROACH</span>.</p>
</header>
<main id="content">
    <div id="container">
        `)
//line internal/web/templates/index.qtpl:33
	if len(p.Members) == 0 {
//line internal/web/templates/index.qtpl:33
		qw422016.N().S(`
            <img id="no-bitches" src="/static/no-bitches.jpg">
        `)
//line internal/web/templates/index.qtpl:35
	} else {
//line internal/web/templates/index.qtpl:35
		qw422016.N().S(`
            `)
//line internal/web/templates/index.qtpl:36
		for _, m := range p.Members {
//line internal/web/templates/index.qtpl:36
			qw422016.N().S(`
                <div class="member">
                    <img src="`)
//line internal/web/templates/index.qtpl:38
			qw422016.E().S(m.AvatarURL)
//line internal/web/templates/index.qtpl:38
			qw422016.N().S(`">
                    <p>`)
//line internal/web/templates/index.qtpl:39
			qw422016.E().S(m.Name)
//line internal/web/templates/index.qtpl:39
			qw422016.N().S(`</p>
                </div>
            `)
//line internal/web/templates/index.qtpl:41
		}
//line internal/web/templates/index.qtpl:41
		qw422016.N().S(`
        `)
//line internal/web/templates/index.qtpl:42
	}
//line internal/web/templates/index.qtpl:42
	qw422016.N().S(`
    </div>
</main>
`)
//line internal/web/templates/index.qtpl:45
}

//line internal/web/templates/index.qtpl:45
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:45
	p.StreamBody(qw422016)
//line internal/web/templates/index.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:45
}

//line internal/web/templates/index.qtpl:45
func (p *IndexPage) Body() string {
//line internal/web/templates/index.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:45
	p.WriteBody(qb422016)
//line internal/web/templates/index.qtpl:45
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:45
	return qs422016
//line internal/web/templates/index.qtpl:45
}
